# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/instrument.xdc

# IP: ip/dds_Instrument/dds_Instrument.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_Instrument || ORIG_REF_NAME==dds_Instrument} -quiet] -quiet
